### ISSUE TITLE
Non-pinned Versions for Supporting Libraries

### ISSUE THREAD

**Issue by kjam** [capeprivacy/cape-python#100]
**Is your feature request related to a problem? Please describe.**
Since many folks will use this library in conjunction with other Python libraries, it is best practice to not pin exact versions but to instead try to allow for a certain base version we have tested with and up. This allows folks to deploy Cape in places where they might need or use a higher or lower library version than the one we normally use. 

**Describe the solution you'd like**
It would be nice to figure out some lower level requirements and use the `>=` in the requirements file so folks can have variance in their versions. This would also solve our deployment issue on CoLab! We should then also add a call for folks to report any bugs they find with newly released versions of libraries.

**Describe alternatives you've considered**
We can continue to pin versions and this will be okay for folks that don't have a lot of other Python libraries installed and running.

**Additional context**
This came in as a feature request from a recent user interview and from my own use of Cape Python on GCP!

**Comment by kjam** [comment]
Follow ups are:

- @kjam to check at what versions we need for CoLab
- @bendecoste found ability to pin to minor versions and up without having the next major version do a breaking change. https://stackoverflow.com/questions/8795617/how-to-pip-install-a-package-with-min-and-max-version-range

**Comment by justin1121** [comment]
Maybe this isn't quite closed up yet. Need some investigation into the colab versions needed.
